version: '3.7'
networks:
  default:
    name: tosc-test16
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  nginx:
    image: nginx:latest
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  db15:
    container_name: postgres15_db
    image: postgres:15
    labels:
      - "5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    restart: unless-stopped
    volumes:
      - .db15/data/:/var/lib/postgresql/data
      - .db15/socket/:/var/run/postgresql/
    ports:
      - 5432:5432

#  ocr:
#    build:
#      context: /home/docky/tosc-base/ocrmypdf
#      dockerfile: Dockerfile
#    container_name: ocr
#    image: tosc-registry:443/ocrmypdf:nld
#    entrypoint: python3
#    restart: unless-stopped
#    expose:
#      - 5000
#    command: [ "webservice.py" ]

  ocrmypdf:
    image: jbarlow83/ocrmypdf
    entrypoint: "python"
    command: "webservice.py"

  kwkhtmltopdf:
    container_name: kwkhtmltopdf
#    image: ghcr.io/acsone/kwkhtmltopdf:0.12.1.3-latest
    image: ghcr.io/acsone/kwkhtmltopdf:0.12.5-latest
    restart: unless-stopped
    expose:
      - 8080

  tosc_test16:
    build: /home/docky/tosc-test16/odoo/
    container_name: tosc_test16
    image: tosc-registry:443/tosc_test16:latest
    environment:
      - MIGRATE=false
      - PYTHONDONTWRITEBYTECODE=true
      - LOCAL_USER_ID=$UID
      - DB_USER=${PGUSER}
      - DB_PASS=${PGPASSWORD}
      - DB_MAXCONN=$DB_MAXCONN
      - DB_HOST=$PGHOST
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - DB_NAME=bo16-test.tosc.nl
      - DB_FILTER=bo16-test.tosc.nl
      - RUNNING_ENV=prod
      - LIST_DB=false
      #     - DEMO=False
      - LIMIT_TIME_CPU=600
      - LIMIT_TIME_REAL=1200
      - WORKERS=3
      - ADDONS_PATH=${ADDONS_PATH_TOSC_TEST16}
      #      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=bo16-test.tosc.nl
      - VIRTUAL_PORT=8069,8072/websocket
      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
      - ODOO_REPORT_URL=http://tosc_test16:8069
#    user: odoo
#    expose:
#      - 8069
#      - 8072
    ports:
      - 8077:8069
      - 8078:8072
    volumes:
#      - /home/docky/tosc-test16/odoo/external-src:/odoo/external-src
#      - /home/docky/tosc-test16/odoo/src/addons:/odoo/src/odoo/addons
#      - /home/docky/tosc-test16/odoo/links:/odoo/links
#      - /home/docky/tosc-test16/odoo/local-src:/odoo/local-src
      - /home/docky/tosc-test16/data:/odoo/data/odoo
#    command: [ "odoo" ]
    command: [ "bash" ]
    stdin_open: true
    tty: true
    extra_hosts:
      - "casa.tosc.nl:10.147.34.251"